/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Ep' at '8/18/17 12:39 PM' with Gradle 2.14.1
 *
 * @author Ep, @date 8/18/17 12:39 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
